version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-soli-ctf
    environment:
      POSTGRES_USER: ctf_soli
      POSTGRES_PASSWORD: ctf_soli_pass
      POSTGRES_DB: ctf_soli_db
    volumes:
      - solipg:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  solipg:
