version: '3.9'

services:
  fastapi:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - db

  celery:
    build: .
    command: celery -A app.tasks worker --loglevel=info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - redis
      - db

  redis:
    image: redis:7

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: ctf_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: