version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ctf_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: fastapi_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      - REDIS_HOST=redis
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/ctf_db
    #entrypoint: ["sh", "-c", "uvicorn app.main:app --host 0.0.0.0 --port 8000 & sleep 3 && python seed.py && tail -f /dev/null"]

  worker:
    build: .
    container_name: celery_worker
    command: celery -A app.tasks worker --loglevel=info
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/code
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_HOST=redis
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/ctf_db

volumes:
  pgdata:
