# Generated by Django 4.2.17 on 2025-05-08 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_problem_port_teamproblem_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='peoblem2_up',
        ),
        migrations.RemoveField(
            model_name='team',
            name='problem1_up',
        ),
    ]
