version: '3.9'

services:
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    restart: always
    ports:
      - "5540:5540"
