# Generated by Django 5.2.1 on 2025-05-25 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_deployment_challenge_remove_deployment_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='port',
        ),
    ]
