version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: mot
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock

  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - celery_worker
      - redis
      - postgres
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  pgdata:
