version: '3.8'

services:
  web:
    build: .
    container_name: flask_api
    depends_on:
      - db
      - redis
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DATABASE_URI=postgresql://postgres:1234@db:5432/ctfdb
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery:
    build: .
    container_name: celery_worker
    command: celery -A docker_tasks worker --loglevel=info
    depends_on:
      - redis
      - db
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DATABASE_URI=postgresql://postgres:1234@db:5432/ctfdb
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ctfdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis_server
    ports:
      - "6379:6379"

volumes:
  postgres_data:
