version: '3.9'

services:
  postgres_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: assignments_db
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis_broker:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  web_app:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: fastapi_service
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    depends_on:
      - postgres_db
      - redis_broker

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery_service
    depends_on:
      - redis_broker
      - postgres_db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  admin_interface:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis_dashboard:
    image: redis/redisinsight:latest
    container_name: redis_dashboard
    restart: always
    ports:
      - "5540:5540"

volumes:
  pg_data:
